server:
  port: 8088

spring:
  redis:
    host: localhost  # IP
    port: 6379  # 端口号
    password: as12346  # 密码
    timeout: 10000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: 5000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接